services:
  scorepanel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_SOCKET_URL: ${REACT_APP_SOCKET_URL}
        REACT_APP_ENCRYPTION_SECRET: ${REACT_APP_ENCRYPTION_SECRET}
        REACT_APP_API_INTERVAL: ${REACT_APP_API_INTERVAL}
        REACT_APP_IS_SOCKET: ${REACT_APP_IS_SOCKET}
        REACT_APP_DEFAULTAUTH: ${REACT_APP_DEFAULTAUTH}
    container_name: scorepanel
    ports:
      - "4000:80"
    restart: unless-stopped
