import { SWITCH, TEXT } from "../../components/Common/Const";

export const ClientConst = [
  {
    name: "fullName",
    label: "FullName",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter FullName.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "userName",
    label: "UserName",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter UserName.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isAllowMultiLogin",
    label: "AllowMultiLogin",
    parentclassName: "",
    defaultValue: false,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isDelete",
    label: "Delete",
    parentclassName: "",
    defaultValue: false,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isEmailVerified",
    label: "EmailVerified",
    parentclassName: "",
    defaultValue: false,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "emailId",
    label: "Email Id",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter Email Id.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isMobileVerified",
    label: "MobileVerified",
    parentclassName: "",
    defaultValue: false,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "mobileNo",
    label: "Mobile No",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter Mobile No.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  }, 
  {
    name: "registrationProcessStatus",
    label: "Process Status",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter Registration Process Status.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isUserActive",
    label: "User Active",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter User Active.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  }, 
  {
    name: "provider",
    label: "Provider",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter Provider.",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "isActive",
    label: "Is Active",
    parentclassName: "",
    defaultValue: true,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
];
