import {
  DATE_TIME_PICKER,
  SELECT,
  SWITCH,
  TEXT,
} from "../../components/Common/Const";

export const EventMarketFields = [
  {
    type: SELECT,
    name: "commentaryId",
    label: "Commentary Type",
    options: [{ label: "Select a Commentary Type", value: "0" }],
    defaultValue: "0",
    isRequired: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SELECT,
    name: "marketTemplateId",
    label: "Market Template",
    options: [{ label: "Select a Market Template", value: "0" }],
    defaultValue: "0",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  // {
  //   type: TEXT,
  //   name: "eventMarketId",
  //   label: "Event Market Id",
  //   isRequired: true,
  //   regexErrorMessage: "Please Enter Event Market Id",
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: TEXT,
  //   name: "commentaryId",
  //   label: "Event Commentary Id",
  //   isRequired: true,
  //   regexErrorMessage: "Please Enter Event Commentary Id",
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: TEXT,
  //   name: "eventRefId",
  //   label: "Event Ref Id",
  //   isRequired: true,
  //   regexErrorMessage: "Please Enter Event Ref Id",
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  {
    type: TEXT,
    name: "inningsId",
    label: "Innings Id",
    isRequired: true,
    regexErrorMessage: "Please Enter Innings Id",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    type: TEXT,
    name: "teamId",
    label: "Team Id",
    isRequired: true,
    regexErrorMessage: "Please Enter Team Id",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    type: TEXT,
    name: "marketName",
    label: "Market",
    isRequired: true,
    regex: /^[a-zA-Z0-9 ]{0,100}$/,
    regexErrorMessage: "Max allowed Characters 100, No Spacial Character",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    type: TEXT,
    name: "margin",
    label: "Margin",
    isRequired: true,
    regexErrorMessage: "Please Enter Margin",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  // {
  //   type: SELECT,
  //   name: "status",
  //   label: "Status",
  //   isRequired: true,
  //   options: [
  //     { label: "Select Status" },
  //     { label: "NotOpen", value: 0 },
  //     { label: "Open", value: 1 },
  //     { label: "Inactive", value: 2 },
  //     { label: "Suspend", value: 3 },
  //     { label: "Close", value: 4 },
  //     { label: "Settled", value: 5 },
  //     { label: "Cancel", value: 6 },
  //   ],
  //   // defaultValue: "0",
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  { //
    type: SWITCH,
    name: "isPredefineMarket",
    label: "Is PredefineMarket",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isPreMatchOnly",
    label: "Is PreMatchOnly",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isPreMatchMarket",
    label: "Is PreMatchMarket",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isAutoCancel",
    label: "Is AutoCancel",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "isOver",
    label: "Over",
    type: SWITCH,
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "over",
    label: "Over",
    dependsOnField: "isOver",
    dependsOnValue: true,
    type: TEXT,
    placeholder: "Overs",
    isRequired: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "isPlayer",
    label: "Player",
    defaultValue: false,
    type: SWITCH,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    name: "playerId",
    label: "Player Id",
    dependsOnField: "isPlayer",
    dependsOnValue: true,
    type: TEXT,
    placeholder: "Player Id",
    isRequired: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "autoOpenType",
    label: "Auto Open Type",
    options: [
      { label: "Select Auto Open Type", value: "0" },
      { label: "Ball", value: "1" },
      { label: "Over", value: "2" },
      { label: "Wicket", value: "3" },
    ],
    type: SELECT,
    defaultValue: false,
    isRequired: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "autoOpen",
    label: "Auto Open",
    isRequired: true,
    regexErrorMessage: "Please Enter Value",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "autoCloseType",
    label: "Auto Close Type",
    isRequired: true,
    options: [
      { label: "Select Auto Close Type", value: "0" },
      { label: "Ball", value: "1" },
      { label: "Over", value: "2" },
      { label: "Wickets", value: "3" },
    ],
    type: SELECT,
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "beforeAutoClose",
    label: "Before Auto Close",
    isRequired: true,
    regexErrorMessage: "Please Enter Value",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "autoSuspendType",
    label: "Auto Suspend Type",
    isRequired: true,
    options: [
      { label: "Select Auto Suspend Type", value: "0" },
      { label: "Ball", value: "1" },
      { label: "Over", value: "2" },
      { label: "Wicket", value: "3" },
    ],
    type: SELECT,
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "beforeAutoSuspend",
    label: "Before Auto Suspend",
    isRequired: true,
    regexErrorMessage: "Please Enter Before Auto Suspend",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isAutoResultSet",
    label: "Is AutoResult Set",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "autoResultType",
    label: "Auto Result Type",
    dependsOnField: "isAutoResultSet",
    isRequired: true,
    options: [
      { label: "Select Auto Open Type", value: "0" },
      { label: "Ball", value: "1" },
      { label: "Over", value: "2" },
      { label: "Wickets", value: "3" },
    ],
    dependsOnValue: true,
    type: SELECT,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isBallStart",
    label: "Is Ball Start",
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "autoResultafterBall",
    label: "Auto Result After Ball",
    isRequired: true,
    regexErrorMessage: "Please Enter Auto Result After Ball",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "afterWicketAutoSuspend",
    label: "After Wicket Auto Suspend",
    isRequired: true,
    regexErrorMessage: "Please Enter After Wicket Auto Suspend",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: TEXT,
    name: "afterWicketNotCreated",
    label: "After Wicket Not Created",
    isRequired: true,
    regexErrorMessage: "Please Enter After Wicket Not Created",
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    type: SWITCH,
    name: "isActive",
    label: "Is Active",
    defaultValue: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  {
    type: SWITCH,
    name: "isAllow",
    label: "Is Allow",
    defaultValue: true,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  { //
    name: "actionType",
    label: "Action Type",
    isRequired: true,
    options: [
      { label: "Select Action Type", value: "0" },
      { label: "winClose", value: "1" },
      { label: "winCloseCancel", value: "2" },
    ],
    type: SELECT,
    defaultValue: false,
    labelColspan: { xs: 12, md: 2, lg: 2 },
    fieldColspan: { xs: 12, md: 4, lg: 4 },
  },
  // { //
  //   type: TEXT,
  //   name: "marketTemplateId",
  //   label: "Market Template Id",
  //   isRequired: true,
  //   regexErrorMessage: "Please Enter Market Template Id",
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: DATE_TIME_PICKER,
  //   name: "eventDate",
  //   label: "Event Date",
  //   isRequired: true,
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: TEXT,
  //   name: "eventTypeName",
  //   label: "Event Name",
  //   isRequired: true,
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: TEXT,
  //   name: "competitionName",
  //   label: "Competition",
  //   isRequired: true,
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
  // {
  //   type: TEXT,
  //   name: "eventName",
  //   label: "Event",
  //   isRequired: true,
  //   labelColspan: { xs: 12, md: 2, lg: 2 },
  //   fieldColspan: { xs: 12, md: 4, lg: 4 },
  // },
];
