import { IMAGE, MULTI_SELECT, SELECT, TEXT } from "../../components/Common/Const";

export const TeamFields = [
    {
        type: SELECT,
        name: "eventTypeId",
        label: "Event Type",
        parentclassName: "",
        isRequired: true,
        requiredErrorMessage: "Please enter event type.",
        options: [{ label: "Select Event Type", value: "0" }],
        defaultValue: "0",
        labelColspan: { xs: 12, md: 2, lg: 2 },
        fieldColspan: { xs: 12, md: 4, lg: 4 }
    },
    {
        type: TEXT,
        name: "teamName",
        label: "Team Name",
        parentclassName: "",
        isRequired: true,
        regex: /^.{0,20}$/,
        regexErrorMessage: "Max allowed Characters 20",
        labelColspan: { xs: 12, md: 2, lg: 2 },
        fieldColspan: { xs: 12, md: 4, lg: 4 },
        requiredErrorMessage: "Please enter team name.",
    },
    {
        type: TEXT,
        name: "teamShortName",
        label: "Short Name",
        parentclassName: "",
        isRequired: true,
        regex: /^.{0,10}$/,
        regexErrorMessage: "Max allowed Characters 10",
        labelColspan: { xs: 12, md: 2, lg: 2 },
        fieldColspan: { xs: 12, md: 4, lg: 4 },
        requiredErrorMessage: "Please enter short name.",
    },
    {
        type: TEXT,
        name: "country",
        label: "Country",
        parentclassName: "",
        regex: /^[a-zA-Z0-9 ]{0,20}$/,
        regexErrorMessage: "Max allowed Characters 20, No Spacial Character",
        labelColspan: { xs: 12, md: 2, lg: 2 },
        fieldColspan: { xs: 12, md: 4, lg: 4 },
    },
    {
        type: IMAGE,
        name: "jersey",
        label: "Jersey Image",
        parentclassName: "",

    },
    {
        type: IMAGE,
        name: "image",
        label: "Team Image",
        parentclassName: "",
    },
    {
        type: MULTI_SELECT,
        name: "playerId",
        label: "Select Players",
        options: [],
        showSelectAll: true,
        labelColspan: { xs: 12, md: 2, lg: 2 },
        fieldColspan: { xs: 12, md: 4, lg: 4 },
    },
]